site_name: System Design Study Notes
site_url: http://system-design-study.shams-nahid.com/
site_description: System Design Study notes
site_author: Shams Nahid

repo_url: https://github.com/bmshamsnahid/system-design-study
edit_uri: ""

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2021 <a href="https://shams-nahid.com/">Shams Nahid</a>.
